name: GiveAll
main: com.harry5573.giveall.Main
version: 2.0b1
author: harry5573
description: GiveAll allows you to give an item (and amount) to every online player.
commands:
  giveall:
    description: Gives all online players an item.